name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t playwright-e2e .
      - name: Run Playwright tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/test-results:/app/test-results playwright-e2e
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: test-results
          retention-days: 7