name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Build Docker image
        run: docker build -t playwright-e2e .
      - name: Run Playwright tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app playwright-e2e
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report